"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.ProblemFactory = exports.MigrationsFactory = exports.MasterFactory = exports.AnswerFactory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var AnswerFactory_1 = require("./AnswerFactory");
__createBinding(exports, AnswerFactory_1, "AnswerFactory");
var MasterFactory_1 = require("./MasterFactory");
__createBinding(exports, MasterFactory_1, "MasterFactory");
var MigrationsFactory_1 = require("./MigrationsFactory");
__createBinding(exports, MigrationsFactory_1, "MigrationsFactory");
var ProblemFactory_1 = require("./ProblemFactory");
__createBinding(exports, ProblemFactory_1, "ProblemFactory");
